# Auto-generated by Terraform (infra/terraform). Do not edit by hand -
# re-run `terraform apply` instead, it will overwrite this file.

[server]
k3s-server ansible_host=${server_public_ip} ansible_user=${ssh_user} private_ip=${server_private_ip}

[agents]
%{ for idx, ip in agent_public_ips ~}
agent-${idx + 1} ansible_host=${ip} ansible_user=${ssh_user}
%{ endfor ~}

[k3s_cluster:children]
server
agents
